server:
  port: 8080
  servlet:
    session:
      timeout: 336h
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/toystory
    username: toystory
    password: toystory
  session:
    redis:
      namespace: spring:ratatouille
      flush-mode: on_save
  security:
    user:
      name: joielee
      password: 1234321
      roles: ADMIN
  data:
    redis:
      host: 127.0.0.1
      port: 6379